//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDusingEFDBFirstinMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class student
    {
        public int RollNo { get; set; }
        public string Name { get; set; }
        public Nullable<int> Age { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> DoB { get; set; }
        public string city { get; set; }
        public Nullable<int> TrainerId { get; set; }
    
        public virtual Trainer Trainer { get; set; }
    }
}
